name: sc_workshops
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py38h294d835_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - ca-certificates=2020.11.8=h5b45459_0
  - certifi=2020.11.8=py38haa244fe_0
  - cffi=1.14.3=py38h0e640b1_1
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - future=0.18.2=py38haa244fe_2
  - icu=67.1=h33f27b4_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.3.4=py38h7b7c402_1
  - ipython=7.19.0=py38hc5df569_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jedi=0.17.2=py38haa244fe_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38haa244fe_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - libblas=3.8.0=20_mkl
  - libcblas=3.8.0=20_mkl
  - libclang=10.0.1=default_hf44288c_1
  - liblapack=3.8.0=20_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=he025d50_3
  - livereload=2.6.3=pyh9f0ad1d_0
  - lunr=0.5.8=py38h32f6830_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py38hab1e662_2
  - mistune=0.8.4=py38h294d835_1002
  - mkdocs=1.1.2=py_0
  - mkl=2020.2=256
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38haa244fe_3
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nltk=3.4.4=py_0
  - notebook=6.1.5=py38haa244fe_0
  - numpy=1.19.4=py38h0cc643e_1
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.4=py38h4c96930_0
  - pandoc=2.11.1.1=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pickleshare=0.7.5=py_1003
  - pip=20.2.4=py_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - prompt_toolkit=3.0.8=hd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.2=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h7ae7562_4
  - pyrsistent=0.17.3=py38h294d835_1
  - python=3.8.4=cpython_h5fd99cc_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pywin32=228=py38h1e8a9f7_0
  - pywinpty=0.5.7=py38h32f6830_1
  - pyyaml=5.3.1=py38hab1e662_1
  - pyzmq=20.0.0=py38h7a0e47e_1
  - qt=5.12.9=hb2cf2c5_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rtree=0.9.4=py38h8b54edf_2
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h9bdc248_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=he774522_1
  - terminado=0.9.1=py38haa244fe_1
  - testpath=0.4.4=py_0
  - tornado=6.1=py38h294d835_0
  - traitlets=5.0.5=py_0
  - trimesh=3.8.12=pyh9f0ad1d_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38haa244fe_4
  - wincertstore=0.2=py38h32f6830_1005
  - winpty=0.4.3=4
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=h0e60522_2
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h62dcd97_1010
  - pip:
      - appdirs==1.4.4
      - colorcet==2.0.2
      - cycler==0.10.0
      - imageio==2.9.0
      - ipycanvas==0.6.0
      - ipydatawidgets==4.1.0
      - ipyevents==0.8.1
      - ipympl==0.5.8
      - ipyvtk-simple==0.1.3
      - itk-core==5.1.1.post1
      - itk-filtering==5.1.1.post1
      - itk-meshtopolydata==0.6.2
      - itk-numerics==5.1.1.post1
      - itkwidgets==0.32.0
      - kiwisolver==1.3.1
      - matplotlib==3.3.3
      - meshio==4.3.5
      - mkdocs-material==6.1.5
      - mkdocs-material-extensions==1.0.1
      - param==1.10.0
      - pillow==8.0.1
      - pyct==0.4.8
      - pymdown-extensions==8.0.1
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pyvista==0.27.2
      - scooby==0.5.6
      - traittypes==0.2.1
      - vtk==9.0.1
      - zstandard==0.14.0
prefix: C:\Programs\Anaconda3\envs\sc_workshops
