name: sc_workshops
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38h50d1736_1002
  - argon2-cffi=20.1.0=py38h7e3306e_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - ca-certificates=2020.11.8=h033912b_0
  - certifi=2020.11.8=py38h50d1736_0
  - cffi=1.14.3=py38h2125817_2
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.9=hb1e8313_2
  - gettext=0.19.8.1=h1f1d5ed_1
  - glib=2.66.1=h9bbe63b_0
  - icu=67.1=hb1e8313_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py38h9bb44b7_1
  - ipython=7.19.0=py38h9bb44b7_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jedi=0.17.2=py38h50d1736_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38h50d1736_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - krb5=1.17.1=h75d18d8_3
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libclang=10.0.1=default_hf57f61e_1
  - libcxx=11.0.0=h439d374_0
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=h7cc5361_13
  - libgfortran5=9.3.0=h7cc5361_13
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=2_openblas
  - libllvm10=10.0.1=h009f743_3
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libpq=12.3=haa216e0_2
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=h4a8c4bd_3
  - llvm-openmp=11.0.0=h73239a0_1
  - lz4-c=1.9.2=hb1e8313_3
  - markupsafe=1.1.1=py38h94c058a_2
  - mistune=0.8.4=py38h7e3306e_1002
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hfb8f7af_2
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - notebook=6.1.5=py38h50d1736_0
  - nspr=4.29=hb1e8313_1
  - nss=3.47=hc0980d9_0
  - numpy=1.19.4=py38hcf469a5_1
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.4=py38hcf432d8_0
  - pandoc=2.11.1.1=hbcb3906_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.2.4=py_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - prompt_toolkit=3.0.8=hd8ed1ab_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.2=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38hca2ab18_4
  - pyrsistent=0.17.3=py38h7e3306e_1
  - python=3.8.5=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pyzmq=20.0.0=py38h9b3f83f_1
  - qt=5.12.9=h717870c_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - rtree=0.9.4=py38hc59ffc2_2
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h5347e94_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h960bd1c_1
  - terminado=0.9.1=py38h50d1736_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_1
  - tornado=6.1=py38h7e3306e_0
  - traitlets=5.0.5=py_0
  - trimesh=3.8.12=pyh9f0ad1d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38h50d1736_4
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.3=h2e338ed_2
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.5=h289c70a_2
  - pip:
      - appdirs==1.4.4
      - colorcet==2.0.2
      - cycler==0.10.0
      - imageio==2.9.0
      - ipycanvas==0.6.0
      - ipydatawidgets==4.1.0
      - ipyevents==0.8.1
      - ipympl==0.5.8
      - ipyvtk-simple==0.1.3
      - itk-core==5.1.1.post1
      - itk-filtering==5.1.1.post1
      - itk-meshtopolydata==0.6.2
      - itk-numerics==5.1.1.post1
      - itkwidgets==0.32.0
      - kiwisolver==1.3.1
      - ladybug-comfort==0.9.40
      - ladybug-core==0.33.3
      - ladybug-geometry==1.22.9
      - lbt-ladybug==0.25.33
      - matplotlib==3.3.3
      - meshio==4.3.5
      - param==1.10.0
      - pillow==8.0.1
      - pyct==0.4.8
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pyvista==0.27.0
      - scooby==0.5.6
      - traittypes==0.2.1
      - vtk==9.0.1
      - zstandard==0.14.0
prefix: /Users/shervinazadi/opt/miniconda3/envs/sc_workshops
